#%RAML 1.0
title: airport-api

types:
  Airport: !include DataType/AirportDataType.raml

/airport:
  /showAll:
    get:
      responses:
        200:
          body:
            application/json:
              type: Airport[]
              example: !include Examples/AirportGetExample.raml

  /addAirport:
    post:
      body:
        application/json:
          type: Airport
          example: !include Examples/AirportPostExample.raml
      responses:
        201:
          body:
            application/json:
              example:
                message: Airport added
  
  /showById/{code}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Airport
              example: !include Examples/AirportExample.raml
        400:
          body:
            application/json:
              example:
                message: Airport not found

  /modifyAirport/{code}:
    put:
      body:
        application/json:
          type: Airport
          example: !include Examples/AirportExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Airport updated
        400:
          body:
            application/json:
              example:
                message: Airport not found

  /deleteAirport/{code}:
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Airport deleted
        400:
          body:
            application/json:
              example:
                message: Airport not found
