#%RAML 1.0
title: booking-api
types:
  Booking : !include DataType/BookingDataType.raml


/booking:
  /viewbooking:
    get:
      responses:
        200:
          body:
            application/json:
              type : Booking[]
              example: !include Examples/BookingGetAllExample.raml
            
  /addBooking:
    post:
      body:
        application/json:
          type: Booking
          example: !include Examples/BookingPostExample.raml
      responses:
        201:
          body:
            application/json:
              example:
                message: Booking added.

  /viewBooking/{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Booking
              example: !include Examples/BookingExample.raml
                  
        400:
          body:
            application/json:
              example:
                message: No booking found

  /modifyBooking/{id}:
    put:
      body:
        application/json:
          type: Booking
          example:
      responses:
        200:
          body:
            application/json:
              type: Booking
              example: !include Examples/BookingExample.raml
        400:
          body:
            application/json:
              example:
                message: No Booking found

  /patchbooking/{id}:
    patch:
      queryParameters:
        ticketCost: 
          required: false
      responses:
        200:
          body:
            application/json:
              
        


  /deleteBooking/{id} :
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Booking deleted

        400:
          body:
            application/json:
              example:
                message: Booking not found