#%RAML 1.0
title: booking-api
types:
  Booking : !include DataType/BookingDataType.raml


/booking:
  /showAllBookings:
    get:
      responses:
        200:
          body:
            application/json:
              type : Booking[]
              example: !include Examples/BookingGetAllExample.raml
            
  /addBooking:
    post:
      body:
        application/json:
          type: Booking
          example: !include Examples/BookingPostExample.raml
      responses:
        201:
          body:
            application/json:
              example:
                message: Booking added.

  /showById/{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Booking
              example: !include Examples/BookingExample.raml
                  
        400:
          body:
            application/json:
              example:
                message: Booking not found

  /showBySfid/{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Booking
              example: !include Examples/BookingExample.raml

        400:
          body:
              application/json:
                example:
                  message: Booking not found

  /modifyBooking/{id}:
    put:
      body:
        application/json:
          type: Booking
          example: !include Examples/BookingExample.raml
      responses:
        200:
          body:
            application/json:
              example: 
                message: Booking modified
        400:
          body:
            application/json:
              example:
                message: Booking not found

  /patchbooking/{id}:
    patch:
      queryParameters:
        noOfPassengers: 
          required: false
      responses:
        200:
          body:
            application/json:
              example:
                message: Booking patched
        400:
          body:
            application/json:
              example:
                message: Booking not found
      
  /deleteBooking/{id} :
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Booking deleted

        400:
          body:
            application/json:
              example:
                message: Booking not found