#%RAML 1.0
title: Flight Management API

types:
  Airport: !include DataType/AirportDataType.raml
  Booking: !include DataType/BookingDataType.raml
  Passenger: !include DataType/PassengerDataType.raml
  Schedule: !include DataType/ScheduleDataType.raml
  ScheduledFlight: !include DataType/ScheduledFlightDataType.raml
  User: !include DataType/UserDataType.raml
  Flight: !include DataType/FlightDataType.raml

/api:
  /airport:
    /showAllAirports:
    get:
      responses:
        200:
          body:
            application/json:
              type: Airport[]
              example: !include Examples/AirportGetAllExample.raml

    /addAirport:
      post:
        body:
          application/json:
            type: Airport
            example: !include Examples/AirportPostExample.raml
        responses:
          201:
            body:
              application/json:
                example:
                  message: Airport added
  
    /showById/{airportCode}:
      get:
        responses:
          200:
            body:
              application/json:
              type: Airport
              example: !include Examples/AirportExample.raml
        400:
          body:
            application/json:
              example:
                message: Airport not found

  /modifyAirport/{airportCode}:
    put:
      body:
        application/json:
          type: Airport
          example: !include Examples/AirportExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Airport updated
        400:
          body:
            application/json:
              example:
                message: Airport not found

  /deleteAirport/{airportCode}:
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: Airport deleted
        400:
          body:
            application/json:
              example:
                message: Airport not found

  /patchAirport/{airportCode}:
    patch:
      queryParameters:
        airportName:
          required: false
        airportLocation:
          required: false
      responses:
          200:
            body:
              application/json:
                example:
                  message: Airport patched
          400:
            body:
              application/json:
                example:
                  message: Airport not found
