#%RAML 1.0
title: flight-api

types:
  Flight: !include DataType/FlightDataType.raml
/flights:
  /showAllFlights :
    get:
      responses:
        200:
          body:
            application/json:
              type: Flight[]
              example: !include /Examples/FlightGetAllExample.raml

  /addFlight:            
    post:
      body:
        application/json:
          type: Flight
          example: !include /Examples/FlightPostExample.raml

  /showByFno/{ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Flight
              example : !include /Examples/FlightExample.raml
        400 :
          body:
            application/json:
              example:
                message : Flight not found

  /deleteByFno/{ID}:        
    delete:
      responses:
        200:
          body:
            application/json:
              example: 
                message: Flight deleted
        400 :
          body:
            application/json:
              example:
                message : Flight not found
  
  /modifyFlight/{Fno}:
    put:
      body:
        application/json:
          type: Flight
          example: !include /Examples/FlightExample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: Flight updated 
        400 :
          body:
            application/json:
              example:
                message : Flight not found

  /patchFlight/{Fno}:
    patch:
      queryParameters:
        availableSeats :
          required: false
      responses:
          200:
            body:
              application/json:
                example:
                    message : Flight patched   
          400:
            body:
              application/json:
                example:
                  message : Flight not found
              