#%RAML 1.0
title: Flight Management API

types:
  Airport: !include DataType/AirportDataType.raml
  Booking: !include DataType/BookingDataType (1).raml
  Passenger: !include DataType/PassengerDataType.raml
  Schedule: !include DataType/ScheduleDataType.raml
  