#%RAML 1.0
title: schedule-api

types:
  Schedule: !include DataType/ScheduleDataType.raml

/schedule:
  /showAll:
    get:
      responses:
        200:
          body:
            application/json:
              type: Schedule[]
              example: !include Examples/ScheduleGetAllExample.raml

  /addSchedule:
    post:
      body:
        application/json:
          type: Schedule
          example: !include Examples/SchedulePostExample.raml
      responses:
        201:
          body:
            application/json:
              example:
                message: Schedule added
  
  /showById/{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Schedule
              example: !include Examples/ScheduleExample.raml
        400:
          body:
            application/json:
              example:
                message: Schedule not found
  
  /modifySchedule/{id}:
    put:
      body:
        application/json:
          type: Schedule
          example: !include Examples/ScheduleExample.raml
      responses:
        200:
          body:
            application/json:
              