#%RAML 1.0 NamedExample
value:

  bookingId: 100
  bookingDate: 2022-11-12T20:00:00
  passengerList: 
     [
       //add list
     ]
  ticketCost: 10000
  sflight:
    scheduleId: 101
  sourceAirport:
    airportCode: 101
    airportName: Indira Gandhi International Airport
    airportLocation: Delhi
  destinationAirport:
    airportCode: 102
    airportName: Chhatrapati Shivaji International Airport
    airportLocation: Mumbai
  arrivalTime: 2022-11-14T20:00:00
  departureTime: 2022-11-14T16:00:00