#%RAML 1.0 NamedExample
value:

  bookingId: 1000
  bookingDate: 2022-11-12T20:00:00
  user:
      userType: Admin
      userId: 45
      userName: Rohit
      userPassword: Rohit@45
      userPhone: 676
      email: rohitsharma@gmail.com
  passengerList: 
        [
      {
        pnrNumber: 101,
         passengerName: Sahil,
         passengerAge: 22,
         passengerUIN: 123456789012,
         luggage: 9.75
      }
    ]
  ticketCost: 10000
  flight:
    sfid: 101
    availableSeats: 90
    flight: 
      carrierName : Indigo
      flightModel: Jet
      flightNumber: 10001
      seatCapacity: 100
    schedule: 
      sid: 101
      sourceAirport:
        airportCode: 101
        airportName: Indira Gandhi International Airport
        airportLocation: Delhi
      destinationAirport:
        airportCode: 102
        airportName: Chhatrapati Shivaji International Airport
        airportLocation: Mumbai
      arrivalTime: 2022-11-14T20:00:00
      departureTime: 2022-11-14T16:00:00
  noOfPassengers: 1