#%RAML 1.0 NamedExample

value:
  -
    carrierName : Indigo
    flightModel: Jet
    flightNumber: 10001
    seatCapacity: 100
  -
    carrierName : SpiceJet
    flightModel: Boeing
    flightNumber: 10002
    seatCapacity: 120

