#%RAML 1.0 NamedExample
value:
  -
    pnrNumber: 101
    passengerName: Sahil
    passengerAge: 22
    passengerUIN: 123456789012
    luggage: 9.75

  -
    pnrNumber: 102
    passengerName: Hemant
    passengerAge: 22
    passengerUIN: 123456789013
    luggage: 10.05