#%RAML 1.0 NamedExample

value:
    availableSeats: 90
    flight: 
      carrierName : Indigo
      flightModel: Jet
      flightNumber: 10001
      seatCapacity: 100
    schedule: 
      arrivalTime: 2022-10-28T16:10:00
      departureTime: 2022-10-28T14:00:00
      destinationAirport : 
        airportCode: "102"
        airportLocation: Mumbai
        airportName: Chhatrapati Shivaji International Airport
      sid: 101
      sourceAirport:
        airportCode: "103"
        airportLocation: Bangalore
        airportName: Kempegowda International Airport
    sfid: 101
