#%RAML 1.0 NamedExample

value:

  -
    sfid : 101
    availableSeats : 90
    flight:
      carrierName : Indigo
      flightModel: Jet
      flightNumber: 10001
      seatCapacity: 100
    schedule: 
      sid: 101
      sourceAirport:
        airportCode: 101
        airportName: Indira Gandhi International Airport
        airportLocation: Delhi
      destinationAirport:
        airportCode: 102
        airportName: Chhatrapati Shivaji International Airport
        airportLocation: Mumbai
      arrivalTime: 2022-11-14T20:00:00
      departureTime: 2022-11-14T16:00:00
  -
    sfid : 102
    availableSeats : 100
    flight:
      carrierName : SpiceJet
      flightModel: Airbus
      flightNumber: 10002
      seatCapacity: 120
    schedule: 
      sid: 102
      sourceAirport:
        airportCode: 101
        airportName: Indira Gandhi International Airport
        airportLocation: Delhi
      destinationAirport:
        airportCode: 102
        airportName: Chhatrapati Shivaji International Airport
        airportLocation: Mumbai
      arrivalTime: 2022-11-14T20:00:00
      departureTime: 2022-11-14T16:00:00
