#%RAML 1.0 NamedExample
value:
  -
   userType: Admin
   userId: 45
   userName: Rohit
   userPassword: Rohit@45
   userPhone: 676
   email: rohitsharma@gmail.com
  -
   userType: User
   userId: 18
   userName: Virat
   userPassword: Virat@18
   userPhone: 8282
   email: virat18@gmail.com
  -
  userType: User
   userId: 18
   userName: Virat
   userPassword: Virat@18
   userPhone: 8282
   email: virat18@gmail.com
  -